ktor {
    deployment {
        port = 9090
        port = ${?PORT}
    }
    application {
        modules = [ com.smach.zapmancer.ApplicationKt.module ]
    }
}

storage {
    provider = "gcs"
    provider = ${?STORAGE_PROVIDER}
    driver = "org.postgresql.Driver"
    driver = ${?STORAGE_DRIVER}
    jdbcUrl = "jdbc:postgresql://localhost:5432/postgres"
    jdbcUrl = ${?STORAGE_JDBC_URL}
    user = "postgres"
    user = ${?STORAGE_USER}
    password = "password"
    password = ${?STORAGE_PASSWORD}
    bucket = "zapmancer-assets"
    bucket = ${?GCS_BUCKET_NAME}

    s3 {
        endpointUrl = "http://localhost:9000"
        endpointUrl = ${?S3_ENDPOINT_URL}
        region = "us-east-1"
        region = ${?S3_REGION}
        accessKey = "admin"
        accessKey = ${?S3_ACCESS_KEY}
        secretKey = "password"
        secretKey = ${?S3_SECRET_KEY}
    }
}

jwt {
    localSecret = "zapmancer-change-this-in-production"
    localSecret = ${?JWT_LOCAL_SECRET}
}

cors {
    allowedHosts = []
    allowedHosts = ${?CORS_ALLOWED_HOSTS}
}

gorse {
    baseUrl = "http://localhost:8088"
    baseUrl = ${?GORSE_URL}
}

openbiometrics {
    baseUrl = "http://localhost:8000"
    baseUrl = ${?OPENBIOMETRICS_URL}
    apiKey = ${?OPENBIOMETRICS_API_KEY}
}

kyc {
    ed25519PrivateKey = ${?KYC_ED25519_PRIVATE_KEY}
}

redis {
    host = "localhost"
    host = ${?REDIS_HOST}
    port = 6379
    port = ${?REDIS_PORT}
    password = ${?REDIS_PASSWORD}
}


