ktor:
  deployment:
    port: "$PORT:9090"
  application:
    modules:
      - com.smach.zapmancer.app.ApplicationKt.module

storage:
  provider: "$STORAGE_PROVIDER:gcs"
  driver: "$STORAGE_DRIVER:org.postgresql.Driver"
  jdbcUrl: "$STORAGE_JDBC_URL:jdbc:postgresql://localhost:5432/postgres"
  user: "$STORAGE_USER:postgres"
  password: "$STORAGE_PASSWORD:password"
  bucket: "$GCS_BUCKET_NAME:zapmancer-assets"
  s3:
    endpointUrl: "$S3_ENDPOINT_URL:http://localhost:9000"
    region: "$S3_REGION:us-east-1"
    accessKey: "$S3_ACCESS_KEY:admin"
    secretKey: "$S3_SECRET_KEY:password"

jwt:
  localSecret: "$JWT_LOCAL_SECRET:zapmancer-change-this-in-production"

cors:
  allowedHosts: []

gorse:
  baseUrl: "$GORSE_URL:http://localhost:8088"
