#!/bin/sh

echo "Running Detekt and Ktlint..."
gradle detekt ktlintCheck

status=$?

if [ "$status" = 0 ] ; then
    echo "Static analysis found no problems."
    exit 0
else
    echo 1>&2 "Static analysis found violations. Please fix them before committing."
    exit 1
fi
