package com.smach.zapmancer.features.projects.state

data class ProjectDetailUiState(
    val id: String = "",
    val category: String = "Engineering",
    val title: String = "High-Frequency Trading Dashboard Core Development",
    val postedTime: String = "2 hours ago",
    val location: String = "Remote (Global)",
    val isPaymentVerified: Boolean = true,
    val projectScope: String = "We are seeking a senior frontend engineer to architect and build the core components of our new real-time HFT monitoring dashboard. The project requires extreme performance optimization, handling up to 10,000 data updates per second with zero UI lag.",
    val deliverables: List<String> = listOf(
        "Low-latency Canvas-based charting engine.",
        "Real-time order book visualization component.",
        "Websocket management layer with robust reconnection logic.",
        "Custom theme engine for high-contrast trading environments.",
    ),
    val skills: List<String> = listOf(
        "TypeScript",
        "React.js",
        "WebAssembly",
        "WebSocket API",
        "Canvas/WebGL",
        "Rust",
        "FinTech Experience",
    ),
    val budgetRange: String = "$12,000 - $18,000",
    val projectType: String = "Fixed Price Project",
    val timeline: String = "6-8 Weeks",
    val estStart: String = "Oct 2024",
    val clientName: String = "QuantStream Labs",
    val clientIndustry: String = "Financial Tech",
    val clientLocation: String = "London, UK",
    val clientProjectsCount: Int = 42,
    val clientRating: Double = 4.9,
    val isSaved: Boolean = false,
    val isClientActive: Boolean = true,
    val isLoading: Boolean = false,
    val isIdentityVerified: Boolean = false,
    val isPhoneVerified: Boolean = false,
)
